const seedUsers = [
  {
    id: 'USR-001',
    companyId: 'BIZ-101',
    name: 'Arjun Mehta',
    role: 'admin',
    email: 'admin@billbhai.com',
    mobileNo: '9870011201',
    username: 'admin',
    password: 'admin123',
    status: 'Active',
  },
  {
    id: 'USR-002',
    companyId: 'BIZ-101',
    name: 'Komal Shah',
    role: 'cashier',
    email: 'cashier@billbhai.com',
    mobileNo: '9870011202',
    username: 'cashier',
    password: 'cashier123',
    status: 'Active',
  },
  {
    id: 'USR-003',
    companyId: 'BIZ-101',
    name: 'Irfan Ali',
    role: 'inventorymanager',
    email: 'inventorymanager@billbhai.com',
    mobileNo: '9870011203',
    username: 'inventorymanager',
    password: 'inventory123',
    status: 'Active',
  },
  {
    id: 'USR-004',
    companyId: 'BIZ-101',
    name: 'Gopal Yadav',
    role: 'deliveryops',
    email: 'deliveryops@billbhai.com',
    mobileNo: '9870011204',
    username: 'deliveryops',
    password: 'delivery123',
    status: 'Active',
  },
  {
    id: 'USR-005',
    companyId: 'BIZ-102',
    name: 'Hemant Rawat',
    role: 'returnhandler',
    email: 'returnhandler@billbhai.com',
    mobileNo: '9870011205',
    username: 'returnhandler',
    password: 'return123',
    status: 'Active',
  },
  {
    id: 'USR-006',
    companyId: 'BIZ-101',
    name: 'Chirag',
    role: 'superuser',
    email: 'chirag@billbhai.com',
    mobileNo: '9870011206',
    username: 'chirag',
    password: 'chirag1234',
    status: 'Active',
  },
  {
    id: 'USR-007',
    companyId: 'BIZ-101',
    name: 'Demo Customer',
    role: 'customer',
    email: 'customer@demo.com',
    mobileNo: '9810001999',
    username: 'customer',
    password: 'customer123',
    status: 'Active',
  },
];

const seedProducts = [
  {
    id: 'P001',
    supplierId: 'SUP-001',
    name: 'Fresh Apples',
    category: 'Fruits',
    barcode: 'BAR-1001',
    price: 120,
    description: 'Fresh red apples',
  },
  {
    id: 'P002',
    supplierId: 'SUP-002',
    name: 'Rice 5kg',
    category: 'Groceries',
    barcode: 'BAR-1002',
    price: 340,
    description: 'Premium rice pack',
  },
  {
    id: 'P003',
    supplierId: 'SUP-003',
    name: 'Milk 1L',
    category: 'Dairy',
    barcode: 'BAR-1003',
    price: 68,
    description: 'Whole milk',
  },
];

const seedOrders = [
  {
    id: 'ORD-4801',
    customerId: 'CUS-001',
    staffId: 'USR-002',
    companyId: 'BIZ-101',
    orderDate: new Date().toISOString(),
    orderType: 'pickup',
    checkoutMode: 'takeaway_now',
    status: 'Processing',
    paymentMethod: 'Cash',
    total: 120,
    itemsCount: 1,
  },
  {
    id: 'ORD-4802',
    customerId: 'CUS-002',
    staffId: 'USR-002',
    companyId: 'BIZ-101',
    orderDate: new Date().toISOString(),
    orderType: 'delivery',
    checkoutMode: 'delivery_now',
    status: 'Processing',
    paymentMethod: 'UPI',
    total: 340,
    itemsCount: 1,
  },
];

module.exports = {
  seedUsers,
  seedProducts,
  seedOrders,
};
