/**
 * SEED DATA: This file contains the initial state of our application.
 * It mirrors the default mock data from the original BillBhai project.
 *
 * Since we are using an in-memory database for Review-4, all services
 * import these constants to populate their internal arrays.
 */

export const seedCompanies = [
  {
    id: 'BIZ-101',
    name: 'FreshKart Central',
    owner: 'Ritu Malhotra',
    adminName: 'Arjun Mehta',
    type: 'Grocery Retail',
    email: 'central@freshkart.in',
    phone: '+91-9870011101',
    gstNo: 'GST101',
    address: 'Delhi, India',
    status: 'Active',
    productsPlan: 'Core POS + Inventory',
    tenureMonths: 32,
    storesCount: 6,
    profit: 1245000,
    paymentDue: 0,
  },
  {
    id: 'BIZ-102',
    name: 'Metro Mart East',
    owner: 'Aman Bedi',
    adminName: 'Shreya Nair',
    type: 'Supermarket',
    email: 'ops@metromarteast.in',
    phone: '+91-9870011102',
    gstNo: 'GST102',
    address: 'Kolkata, India',
    status: 'Active',
    productsPlan: 'Billing + Returns',
    tenureMonths: 18,
    storesCount: 4,
    profit: 842000,
    paymentDue: 15000,
  },
];

export const seedUsers = [
  {
    id: 'USR-001',
    companyId: 'BIZ-101',
    name: 'Arjun Mehta',
    role: 'admin',
    email: 'admin@billbhai.com',
    mobileNo: '9870011201',
    username: 'admin',
    password: 'admin123',
    status: 'Active',
  },
  {
    id: 'USR-002',
    companyId: 'BIZ-101',
    name: 'Komal Shah',
    role: 'cashier',
    email: 'cashier@billbhai.com',
    mobileNo: '9870011202',
    username: 'cashier',
    password: 'cashier123',
    status: 'Active',
  },
  {
    id: 'USR-003',
    companyId: 'BIZ-101',
    name: 'Irfan Ali',
    role: 'inventorymanager',
    email: 'inventorymanager@billbhai.com',
    mobileNo: '9870011203',
    username: 'inventorymanager',
    password: 'inventory123',
    status: 'Active',
  },
  {
    id: 'USR-004',
    companyId: 'BIZ-101',
    name: 'Gopal Yadav',
    role: 'deliveryops',
    email: 'deliveryops@billbhai.com',
    mobileNo: '9870011204',
    username: 'deliveryops',
    password: 'delivery123',
    status: 'Active',
  },
  {
    id: 'USR-005',
    companyId: 'BIZ-102',
    name: 'Hemant Rawat',
    role: 'returnhandler',
    email: 'returnhandler@billbhai.com',
    mobileNo: '9870011205',
    username: 'returnhandler',
    password: 'return123',
    status: 'Active',
  },
  {
    id: 'USR-006',
    companyId: 'BIZ-101',
    name: 'Chirag',
    role: 'superuser',
    email: 'chirag@billbhai.com',
    mobileNo: '9870011206',
    username: 'chirag',
    password: 'chirag1234',
    status: 'Active',
  },
  {
    id: 'USR-007',
    companyId: 'BIZ-101',
    name: 'Demo Customer',
    role: 'customer',
    email: 'customer@demo.com',
    mobileNo: '9810001999',
    username: 'customer',
    password: 'customer123',
    status: 'Active',
  },
];

export const seedCustomers = [
  {
    id: 'CUS-001',
    companyId: 'BIZ-101',
    name: 'Rahul Sharma',
    mobileNo: '9810001001',
    email: 'rahul@example.com',
    address: '12, MG Road, Sector 14',
  },
  {
    id: 'CUS-002',
    companyId: 'BIZ-101',
    name: 'Priya Patel',
    mobileNo: '9810001002',
    email: 'priya@example.com',
    address: 'A-204, Green Park',
  },
  {
    id: 'CUS-003',
    companyId: 'BIZ-101',
    name: 'Amit Kumar',
    mobileNo: '9810001003',
    email: 'amit@example.com',
    address: 'Plot 7, Industrial Area',
  },
  {
    id: 'CUS-004',
    companyId: 'BIZ-101',
    name: 'Sneha Gupta',
    mobileNo: '9810001004',
    email: 'sneha@example.com',
    address: '302, Lotus Tower',
  },
  {
    id: 'CUS-005',
    companyId: 'BIZ-101',
    name: 'Vikram Joshi',
    mobileNo: '9810001005',
    email: 'vikram@example.com',
    address: 'H.No 15, Civil Lines',
  },
];

export const seedSuppliers = [
  {
    id: 'SUP-001',
    name: 'Agarwal Traders',
    mobileNo: '9811544101',
    email: 'agarwal@traders.in',
    address: 'Delhi',
    gstNo: 'GSTSUP001',
  },
  {
    id: 'SUP-002',
    name: 'Sharma Wholesale',
    mobileNo: '9891722055',
    email: 'sharma@wholesale.in',
    address: 'Delhi',
    gstNo: 'GSTSUP002',
  },
  {
    id: 'SUP-003',
    name: 'Fortune Dist.',
    mobileNo: '9900411233',
    email: 'fortune@dist.in',
    address: 'Mumbai',
    gstNo: 'GSTSUP003',
  },
  {
    id: 'SUP-004',
    name: 'City Dairy',
    mobileNo: '9800011004',
    email: 'city@dairy.in',
    address: 'Delhi',
    gstNo: 'GSTSUP004',
  },
  {
    id: 'SUP-005',
    name: 'SnackHub Foods',
    mobileNo: '9800011005',
    email: 'snackhub@foods.in',
    address: 'Bangalore',
    gstNo: 'GSTSUP005',
  },
  {
    id: 'SUP-006',
    name: 'Cool Bev',
    mobileNo: '9800011006',
    email: 'cool@bev.in',
    address: 'Pune',
    gstNo: 'GSTSUP006',
  },
  {
    id: 'SUP-007',
    name: 'HomeSpark Supplies',
    mobileNo: '9800011007',
    email: 'homespark@supplies.in',
    address: 'Chennai',
    gstNo: 'GSTSUP007',
  },
];

export const seedProducts = [
  {
    id: 'P001',
    supplierId: 'SUP-001',
    name: 'Basmati Rice',
    category: 'Groceries',
    barcode: 'BAR001',
    price: 380,
    size: '5kg',
    description: 'Premium basmati rice',
  },
  {
    id: 'P002',
    supplierId: 'SUP-002',
    name: 'Toor Dal',
    category: 'Groceries',
    barcode: 'BAR002',
    price: 120,
    size: '1kg',
    description: 'Yellow split pigeon peas',
  },
  {
    id: 'P003',
    supplierId: 'SUP-003',
    name: 'Refined Oil',
    category: 'Groceries',
    barcode: 'BAR003',
    price: 155,
    size: '1L',
    description: 'Refined sunflower oil',
  },
  {
    id: 'P004',
    supplierId: 'SUP-004',
    name: 'Amul Butter',
    category: 'Dairy',
    barcode: 'BAR004',
    price: 275,
    size: '500g',
    description: 'Pasteurised butter',
  },
  {
    id: 'P005',
    supplierId: 'SUP-004',
    name: 'Milk',
    category: 'Dairy',
    barcode: 'BAR005',
    price: 60,
    size: '1L',
    description: 'Full cream milk',
  },
  {
    id: 'P006',
    supplierId: 'SUP-005',
    name: 'Bread Loaf',
    category: 'Snacks',
    barcode: 'BAR006',
    price: 45,
    size: 'Regular',
    description: 'Whole wheat bread',
  },
  {
    id: 'P007',
    supplierId: 'SUP-005',
    name: 'Maggi Noodles',
    category: 'Snacks',
    barcode: 'BAR007',
    price: 54,
    size: 'Pack of 4',
    description: 'Instant noodles',
  },
  {
    id: 'P008',
    supplierId: 'SUP-006',
    name: 'Tea Powder',
    category: 'Beverages',
    barcode: 'BAR008',
    price: 160,
    size: '250g',
    description: 'Premium tea',
  },
  {
    id: 'P009',
    supplierId: 'SUP-006',
    name: 'Coffee Jar',
    category: 'Beverages',
    barcode: 'BAR009',
    price: 180,
    size: '100g',
    description: 'Instant coffee',
  },
  {
    id: 'P010',
    supplierId: 'SUP-001',
    name: 'Atta Flour',
    category: 'Groceries',
    barcode: 'BAR010',
    price: 248,
    size: '5kg',
    description: 'Whole wheat flour',
  },
  {
    id: 'P011',
    supplierId: 'SUP-002',
    name: 'Sugar',
    category: 'Groceries',
    barcode: 'BAR011',
    price: 48,
    size: '1kg',
    description: 'Refined sugar',
  },
  {
    id: 'P012',
    supplierId: 'SUP-004',
    name: 'Paneer',
    category: 'Dairy',
    barcode: 'BAR012',
    price: 78,
    size: '200g',
    description: 'Fresh cottage cheese',
  },
  {
    id: 'P013',
    supplierId: 'SUP-004',
    name: 'Curd Cup',
    category: 'Dairy',
    barcode: 'BAR013',
    price: 26,
    size: '200g',
    description: 'Fresh curd',
  },
  {
    id: 'P014',
    supplierId: 'SUP-005',
    name: 'Potato Chips',
    category: 'Snacks',
    barcode: 'BAR014',
    price: 20,
    size: 'Classic',
    description: 'Salted potato chips',
  },
  {
    id: 'P015',
    supplierId: 'SUP-005',
    name: 'Biscuits',
    category: 'Snacks',
    barcode: 'BAR015',
    price: 12,
    size: 'Single Pack',
    description: 'Glucose biscuits',
  },
  {
    id: 'P016',
    supplierId: 'SUP-006',
    name: 'Orange Juice',
    category: 'Beverages',
    barcode: 'BAR016',
    price: 42,
    size: '500ml',
    description: 'Fresh orange juice',
  },
  {
    id: 'P017',
    supplierId: 'SUP-006',
    name: 'Mineral Water',
    category: 'Beverages',
    barcode: 'BAR017',
    price: 20,
    size: '1L',
    description: 'Packaged drinking water',
  },
  {
    id: 'P018',
    supplierId: 'SUP-007',
    name: 'Bath Soap',
    category: 'Home Care',
    barcode: 'BAR018',
    price: 34,
    size: 'Single',
    description: 'Herbal bath soap',
  },
  {
    id: 'P019',
    supplierId: 'SUP-007',
    name: 'Dishwash Liquid',
    category: 'Home Care',
    barcode: 'BAR019',
    price: 58,
    size: '250ml',
    description: 'Lemon dishwash liquid',
  },
  {
    id: 'P020',
    supplierId: 'SUP-007',
    name: 'Detergent Powder',
    category: 'Home Care',
    barcode: 'BAR020',
    price: 96,
    size: '1kg',
    description: 'Washing powder',
  },
];

export const seedInventory = [
  {
    id: 'INV-001',
    productId: 'P001',
    stockAvailable: 145,
    reorderLevel: 20,
    location: 'Shelf A1',
    lastUpdated: '2026-02-17T09:00:00Z',
    status: 'In Stock',
  },
  {
    id: 'INV-002',
    productId: 'P002',
    stockAvailable: 230,
    reorderLevel: 20,
    location: 'Shelf A2',
    lastUpdated: '2026-02-17T09:00:00Z',
    status: 'In Stock',
  },
  {
    id: 'INV-003',
    productId: 'P003',
    stockAvailable: 18,
    reorderLevel: 20,
    location: 'Shelf A3',
    lastUpdated: '2026-02-17T09:00:00Z',
    status: 'Low Stock',
  },
  // Additional inventory entries from user (sanitized)
  {
    id: 'INV-004',
    productId: 'P010',
    stockAvailable: 122,
    reorderLevel: 15,
    location: 'Shelf A4',
    lastUpdated: '2026-02-17T09:00:00Z',
    status: 'In Stock',
  },
  {
    id: 'INV-005',
    productId: 'P011',
    stockAvailable: 64,
    reorderLevel: 10,
    location: 'Shelf A5',
    lastUpdated: '2026-02-17T09:00:00Z',
    status: 'In Stock',
  },
  {
    id: 'INV-006',
    productId: 'P012',
    stockAvailable: 21,
    reorderLevel: 25,
    location: 'Shelf B1',
    lastUpdated: '2026-02-17T09:00:00Z',
    status: 'Low Stock',
  },
  {
    id: 'INV-007',
    productId: 'P013',
    stockAvailable: 88,
    reorderLevel: 10,
    location: 'Shelf B2',
    lastUpdated: '2026-02-17T09:00:00Z',
    status: 'In Stock',
  },
  {
    id: 'INV-008',
    productId: 'P005',
    stockAvailable: 14,
    reorderLevel: 20,
    location: 'Shelf B3',
    lastUpdated: '2026-02-17T09:00:00Z',
    status: 'Low Stock',
  },
  {
    id: 'INV-009',
    productId: 'P014',
    stockAvailable: 172,
    reorderLevel: 15,
    location: 'Shelf C1',
    lastUpdated: '2026-02-17T09:00:00Z',
    status: 'In Stock',
  },
  {
    id: 'INV-010',
    productId: 'P015',
    stockAvailable: 154,
    reorderLevel: 15,
    location: 'Shelf C2',
    lastUpdated: '2026-02-17T09:00:00Z',
    status: 'In Stock',
  },
  {
    id: 'INV-011',
    productId: 'P016',
    stockAvailable: 37,
    reorderLevel: 10,
    location: 'Shelf D1',
    lastUpdated: '2026-02-17T09:00:00Z',
    status: 'In Stock',
  },
  {
    id: 'INV-012',
    productId: 'P017',
    stockAvailable: 9,
    reorderLevel: 15,
    location: 'Shelf D2',
    lastUpdated: '2026-02-17T09:00:00Z',
    status: 'Critical',
  },
  {
    id: 'INV-013',
    productId: 'P019',
    stockAvailable: 48,
    reorderLevel: 10,
    location: 'Shelf E1',
    lastUpdated: '2026-02-17T09:00:00Z',
    status: 'In Stock',
  },
  {
    id: 'INV-014',
    productId: 'P020',
    stockAvailable: 0,
    reorderLevel: 10,
    location: 'Shelf E2',
    lastUpdated: '2026-02-17T09:00:00Z',
    status: 'Out of Stock',
  },
];

export const seedOrders = [
  {
    id: 'ORD-4829',
    customerId: 'CUS-001',
    customerName: 'Rahul Sharma',
    customerAddress: '12, MG Road, Sector 14',
    staffId: 'USR-002',
    companyId: 'BIZ-101',
    orderDate: '2026-02-17T16:42:00Z',
    orderType: 'delivery',
    checkoutMode: 'prepaid_delivery',
    status: 'Processing',
    discountAmount: 0,
    paymentMethod: 'Paid Upfront',
    total: 4280,
  },
  {
    id: 'ORD-4828',
    customerId: 'CUS-002',
    customerName: 'Priya Patel',
    customerAddress: 'A-204, Green Park',
    staffId: 'USR-002',
    companyId: 'BIZ-101',
    orderDate: '2026-02-17T16:05:00Z',
    orderType: 'delivery',
    checkoutMode: 'cod_delivery',
    status: 'Processing',
    discountAmount: 0,
    paymentMethod: 'COD',
    total: 980,
  },
];

export const seedOrderItems = [
  {
    id: 'OI-001',
    orderId: 'ORD-4829',
    productId: 'P001',
    quantity: 1,
    itemPrice: 380,
  },
  {
    id: 'OI-002',
    orderId: 'ORD-4829',
    productId: 'P002',
    quantity: 2,
    itemPrice: 120,
  },
  {
    id: 'OI-003',
    orderId: 'ORD-4829',
    productId: 'P003',
    quantity: 1,
    itemPrice: 155,
  },
  {
    id: 'OI-004',
    orderId: 'ORD-4828',
    productId: 'P003',
    quantity: 1,
    itemPrice: 450,
  },
];

export const seedBills = [
  {
    billNo: 'BILL-001',
    orderId: 'ORD-4829',
    billDate: '2026-02-17T14:33:00Z',
    taxAmount: 62.5,
    discountAmount: 0,
  },
  {
    billNo: 'BILL-002',
    orderId: 'ORD-4828',
    billDate: '2026-02-17T13:46:00Z',
    taxAmount: 22.5,
    discountAmount: 0,
  },
];

export const seedPayments = [
  {
    id: 'PAY-001',
    billNo: 'BILL-001',
    paymentDate: '2026-02-17T14:34:00Z',
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    amountPaid: 1250,
  },
  {
    id: 'PAY-002',
    billNo: 'BILL-002',
    paymentDate: '2026-02-17T13:47:00Z',
    paymentMethod: 'Cash',
    paymentStatus: 'Paid',
    amountPaid: 450,
  },
];

export const seedDeliveries = [
  {
    id: 'DEL-901',
    orderId: 'ORD-4829',
    customerName: 'Rahul Sharma',
    address: '12, MG Road, Sector 14',
    partnerName: 'Rajesh K.',
    dispatchDate: '2026-02-17',
    deliveryDate: null,
    status: 'Pending',
  },
  {
    id: 'DEL-900',
    orderId: 'ORD-4828',
    customerName: 'Priya Patel',
    address: 'A-204, Green Park',
    partnerName: 'Sunil M.',
    dispatchDate: '2026-02-17',
    deliveryDate: null,
    status: 'In Transit',
  },
];

export const seedReturns = [
  {
    id: 'RET-221',
    companyId: 'BIZ-101',
    orderId: 'ORD-4828',
    staffId: 'USR-005',
    returnDate: '2026-02-17',
    reason: 'Damaged',
    refundAmount: 170,
    status: 'Pending',
    returnType: 'refund',
    product: 'Refined Oil',
    qty: 1,
    requestedBy: 'Walk-in',
  },
  {
    id: 'RET-220',
    companyId: 'BIZ-101',
    orderId: 'ORD-4829',
    staffId: 'USR-005',
    returnDate: '2026-02-17',
    reason: 'Expired',
    refundAmount: 58,
    status: 'Pending',
    returnType: 'refund',
    product: 'Milk Pack',
    qty: 1,
    requestedBy: 'POS Counter',
  },
];
